CMakeLists.txt

Signed-off-by: liulanzheng <lanzheng.liulz@alibaba-inc.com>

add photon static library

---

README.md

Reverts alibaba/PhotonLibOS#18

Revert "Add 'Related project' subsection in README"

---

README.md
examples/perf/net-perf.cpp
thread/test/test.cpp
thread/thread.cpp
thread/thread.h

- update net-perf
- add thread_migrate

Multiple changes

---

.github/workflows/ci.yml
CMakeLists.txt
README.md
common/checksum/crc32c.cpp
common/checksum/crc32c.h
examples/perf/net-perf.cpp
examples/simple/simple.cpp
net/http/headers.cpp
net/socket.cpp
thread/README.md
thread/test/test.cpp
thread/thread.cpp
thread/thread.h
thread/thread11.h

- Fix compiling with ARM CPU
- Fix a HTTP client bug

Fix compiling with ARM CPU

---

thread/thread.h

locker can't use [CTAD](https://en.cppreference.com/w/cpp/language/class_template_argument_deduction)

Fix: locker can't use CTAD

---

common/callback.h
net/curl.cpp
net/curl.h
thread/test/CMakeLists.txt
thread/test/test-lib-data.cpp
thread/thread.cpp

1. Some fix on libcurl adaptor, change order of libcurl environment finish.
2. Photon thread alloc/dealloc change to a static object, instead of singleton instance, should get better performance.

Some fix and change on curl adaptor and photon thread alloc/dealloc hook

---

fs/httpfs/httpfs.h
fs/httpfs/httpfs_v2.cpp
net/http/message.cpp
net/http/test/client_function_test.cpp
net/http/url.cpp
net/http/url.h

- for passing in an external http client to httpfs v2
- fix the issue where the path of the URL is missing a leading "/"

enhance for http

---

doc/docs/api/network.md
examples/perf/net-perf.cpp
examples/rpc/server.cpp
examples/simple/simple.cpp
io/fstack-dpdk.cpp
net/datagram_socket.h
net/http/message.cpp
net/http/test/client_function_test.cpp
net/http/test/client_tls_test.cpp
net/http/test/server_function_test.cpp
net/http/test/server_perf.cpp
net/kernel_socket.cpp
net/security-context/test/test-sasl.cpp
net/security-context/test/test.cpp
net/socket.h
net/test/test-ipv6.cpp
net/test/test-server.cpp
net/test/test-udp.cpp
net/test/test.cpp
net/test/test_sockpool.cpp
net/utils-stdstring.h
rpc/rpc.cpp
rpc/test/test.cpp

socket api do not distinguish IPv4 or IPv6
refinement to bind() function series

socket api do not distinguish IPv4 or IPv6

---

common/lockfree_queue.h
thread/test/CMakeLists.txt
thread/workerpool.cpp

RingChannel shows low performance when lots of async_call sending to 
should not wait in semaphore too much frequently

Improve heave load performance in `RingChannel`

---

net/base_socket.h
net/datagram_socket.cpp
net/kernel_socket.cpp
net/socket.h
net/test/test.cpp

The instantiation of sockaddr will lose information

---

common/string-keyed.h
net/http/cookie_jar.cpp
thread/test/perf_usleepdefer_semaphore.cpp

map_string_kv that stores k and v together, to save one allocation.

map_string_kv (no test yet)

---

fs/localfs.cpp

fix readdir for localfs by Qihui Lin

fix readdir for localfs

---

common/alog.cpp
common/alog.h
fs/localfs.cpp
thread/thread.cpp

Pick fixes from Release/0.6 to Release/0.7
including alog and localfs fixes

Pick fixes from Release/0.6 to Release/0.7

---

common/string-keyed.h
common/test/test.cpp
fs/httpfs/httpfs_v2.cpp

make map_string_kv ready for httpfs_v2

map_string_kv ready for httpfs_v2

---

CMakeLists.txt
common/alog.h
common/expirecontainer.h
net/http/message.cpp
net/http/test/client_tls_test.cpp
thread/test/test-pooled-stack-allocator.cpp

fix gcc6 compile failure

---

examples/perf/multi-conn-perf.cpp
include/photon/net/iostream.h
net/iostream.cpp
net/iostream.h
net/test/test.cpp

This adaptor can be used in scenarios such as redis-cpp:
https://github.com/tdv/redis-cpp

adaptor for ISocketStream to std::iostream

---

net/curl.h

Remove some outdated libcurl option usage in curl wrapper header (#440)

---

CMakeLists.txt
ecosystem/CMakeLists.txt

Just using 0.5.0 released single-file header.

Add RapidYAML as ecosystem libs

---

common/timeout.h
thread/future.h
thread/std-compat.h
thread/test/test-std-compat.cpp

Wrap photon::Future/Promise as std_compat::future/promise, which is copyable/movable, and similar to std ones.

std_compat promise/future

---

net/utils.cpp

remove from dnscache for empty IPAddrList

fix dns discard

---

net/http/client.cpp
net/http/client.h
net/http/test/client_function_test.cpp

merge into release/0.6, as overlaybd is still using release/0.6 and there is a demand from overlaybd users for customizing user-agent.

support customized UserAgent in http client

---

thread/awaiter.h

ref: https://stackoverflow.com/questions/27726818/stdcondition-variablewait-for-exits-immediately-when-given-stdchronodura

fix suspend timeout for Awaiter<StdContext>

---

fs/async_filesystem.cpp
fs/exportfs.cpp
fs/test/CMakeLists.txt
fs/test/mock.h
fs/test/test_exportfs.cpp

fix dead lock in ExportPerformer

---

io/iouring-wrapper.cpp
rpc/test/test.cpp

using io_uring_free_probe() instead of free()

using io_uring_free_probe()

---

thread/stack-allocator.cpp

refactoring.
fix allocation larger that max slot size.

Make PooledStackAllocator implemention more clear, and fix

---

common/objectcachev2.h
common/test/CMakeLists.txt

* using atomic load/store to avoid using lock in box update/read.
* no more extract trick. it seems have problems.

ObjCache V2 remove reflock

---

thread/stack-allocator.cpp

Fix miscalculating in-pool size of pooled stack allocator.

Fix pooled stack allocator in-pool size calculation

---

net/http/client.cpp
net/http/client.h
net/kernel_socket.cpp
net/socket.h

For now, only retrieving the source IP from environment variables is supported.

support sending requests from different IP for HTTP client

---

net/http/client.cpp
net/http/client.h
net/http/message.h
net/http/test/client_function_test.cpp

> add set body buffer for http client
Signed-off-by: liulanzheng <lanzheng.liulz@alibaba-inc.com>

[Pick][0.8 to main] | add set body buffer for http client

---

common/estring.h
net/http/client.cpp
net/http/server.cpp

> extract c_str for estring_view

[Pick][0.8 to main] | extract c_str for estring_view

---

net/socket.h
net/test/test-ipv6.cpp

> redefine undefined() in EndPoint

[Pick][0.8 to main] | redefine undefined() in EndPoint

---

rpc/rpc.h

> Make  with one argument able to be call

[Pick][0.7 to 0.8] | Make with one argument able to be call

---

rpc/rpc.h

> Make  with one argument able to be call

[Pick][0.8 to main] | Make with one argument able to be call

---

.github/workflows/images/base/Dockerfile
.github/workflows/images/fstack/Dockerfile

Add build deps in CI baseimg

---

net/utils.cpp

> fix potential race condition in DefaultResolver when discard_cache()

[Pick][0.8 to main] | fix potential race condition in DefaultResolver when discard_cache()

---

common/enumerable.h
fs/localfs.cpp
fs/path.cpp
fs/path.h
fs/test/test.cpp

Fix path Walker when using enumerate #715

fix on path Walker

---

fs/localfs.cpp
fs/path.cpp
fs/path.h
fs/test/test.cpp

[Pick][0.7 to 0.8] | fix on path Walker (#719)

---

fs/localfs.cpp
fs/path.cpp
fs/path.h
fs/test/test.cpp

> fix on path Walker (#719) (#720)

[Pick][0.8 to main] | fix on path Walker (#719) (#720)

---

net/http/headers.cpp
net/http/url.cpp
net/http/url.h

> minor update for http url and headers
Signed-off-by: liulanzheng <lanzheng.liulz@alibaba-inc.com>

[Pick][0.8 to main] | minor update for http url and headers

---

examples/perf/io-perf.cpp

> io-perf example support workpool

[Pick][0.8 to main] | io-perf example support workpool

---

net/curl.cpp

If curl time out, msg will return CURLMSG_DONE with error code in data result.
CURLMSG_DONE only stands for message transfer is done.
https://curl.se/libcurl/c/curl_multi_info_read.html

Fix curl timeout return code handling

---

common/alog.cpp
net/http/cookie_jar.cpp
thread/thread.cpp

[Pick][0.8 to main] | make now monotonic

---

net/http/cookie_jar.cpp
net/http/headers.cpp
net/http/headers.h
net/http/parser.h
net/http/test/cookie_jar_test.cpp

* fix a typo in header
* add support for ```Max-Age```, in addition to ```Expires```

better cookie impl

---

thread/workerpool.cpp

1. Similar to https://github.com/alibaba/PhotonLibOS/pull/735.  Allow init Workpool from non-photon threads
2. Increase ring size of Workpool. Avoid slow task run out of space of ring buffer.

Allow init Workpool from non-photon threads(std::threads); Increase ring size of Workpool

---

net/http/client.cpp

> enhance at_photon_fini() in PooledDialer
Signed-off-by: liulanzheng <lanzheng.liulz@alibaba-inc.com>

[Pick][0.8 to main] | enhance at_photon_fini() in PooledDialer

---

rpc/rpc.cpp

RPC AsyncServe able to access pointer `ctx` before first thread_yield_to, but after that, it should not access is since it might already destructed.

Fix on RPC async_serve accessing count after context call

---

.github/workflows/ci.linux.arm.yml
common/consistent-hash-map.h
common/enumerable.h
common/executor/executor.h
common/expirecontainer.h
common/test/test.cpp
common/test/test_objcache.cpp
common/timeout.h
examples/sync-primitive/sync-primitive.cpp
fs/async_filesystem.cpp
fs/exportfs.cpp
fs/test/test.cpp
thread/thread.cpp
thread/workerpool.cpp

Thanks @f0cii helps found and fix this problem.
Co-authored-by: f0cii [2201441955@qq.com](mailto:2201441955@qq.com)

make it compiles with C++17/20/23

---

.github/workflows/ci.linux.arm.yml
common/consistent-hash-map.h
common/enumerable.h
common/executor/executor.h
common/expirecontainer.h
common/test/test.cpp
common/test/test_objcache.cpp
common/timeout.h
examples/sync-primitive/sync-primitive.cpp
fs/async_filesystem.cpp
fs/exportfs.cpp
fs/test/test.cpp
thread/thread.cpp
thread/workerpool.cpp

> make it compiles with C++17/20/23

[Pick][0.8 to main] | make it compiles with C++17/20/23

---

.github/workflows/auto-pr-autodelete.yml

> Make autopr cleanup using autopr secret

[Pick][0.7 to 0.8] | Make autopr cleanup using autopr secret

---

.github/workflows/auto-pr-autodelete.yml

> Make autopr cleanup using autopr secret

[Pick][0.8 to 0.9] | Make autopr cleanup using autopr secret

---

.github/workflows/auto-pr-autodelete.yml

> Make autopr cleanup using autopr secret

[Pick][0.9 to main] | Make autopr cleanup using autopr secret

---

common/string-keyed.h
examples/perf/net-perf.cpp
fs/test/test.cpp
net/http/test/client_function_test.cpp
rpc/test/test-rpc-message.cpp

> fix compile 0.8 with clang17 (#796)

[Pick][0.8 to 0.9] | fix compile 0.8 with clang17 (#796)

---

common/string-keyed.h
examples/perf/net-perf.cpp
fs/test/test.cpp
net/http/test/client_function_test.cpp
rpc/test/test-rpc-message.cpp

> fix compile 0.8 with clang17 (#796) (#798)
Co-authored-by: Huiba Li <huiba.lhb@alibaba-inc.com>

[Pick][0.9 to main] | fix compile 0.8 with clang17 (#796) (#798)

---

net/utils.cpp

https://github.com/alibaba/PhotonLibOS/issues/794

update Callback in net/utils.cpp

---

.github/workflows/auto-pr-precise.yml

> FIX autopr when commit message contains quota ' character (#812)

[Pick][0.7 to 0.8] | FIX autopr when commit message contains quota ' character (#812)

---

.github/workflows/auto-pr-precise.yml

> FIX autopr when commit message contains quota ' character (#812)

[Pick][0.8 to 0.9] | FIX autopr when commit message contains quota ' character (#812)

---

.github/workflows/auto-pr-precise.yml

> FIX autopr when commit message contains quota ' character (#812) (#814)

[Pick][0.9 to main] | FIX autopr when commit message contains quota ' character (#812) (#814)

---

fs/fuse_adaptor.cpp

This PR addresses a memory leak in the fuse_adptor component when using libfuse3. The issue arises because the fuse_session_process_buf() function does not free the memory allocated for fuse_buf after processing requests, requiring applications to manually manage memory to prevent leaks. We use an IdentityPool object to centrally manage fuse_buf allocation and cleanup.

fuse_adaptor: fix memory leaks in fuse_adptor by using IdentityPool

---

fs/fuse_adaptor.cpp

> fuse_adaptor: fix memory leaks in fuse_adptor by using IdentityPool
This PR addresses a memory leak in the fuse_adptor component when using
libfuse3. The issue arises because the fuse_session_process_buf() function
does not free the memory allocated for fuse_buf after processing requests,
requiring applications to manually manage memory to prevent leaks. We use
an IdentityPool object to centrally manage fuse_buf allocation and cleanup.

[Pick][0.9 to main] | fuse_adaptor: fix memory leaks in fuse_adptor by using IdentityPool

---

net/http/url.cpp

[Pick][0.8 to 0.9] | fix url escape/unescape

---

photon.cpp

> fini_hook should clear after executed (#839)

[Pick][0.8 to 0.9] | fini_hook should clear after executed (#839)

---

net/rsocket/rsocket.cpp

[Pick][0.9 to main] | Make rsocket less latency

---

photon.cpp

> fini_hook should clear after executed (#839)

[Pick][0.9 to main] | fini_hook should clear after executed (#839)

---

net/utils.cpp

> fix race and leak in DefaultResolver

[Pick][0.8 to 0.9] | fix race and leak in DefaultResolver

---

.github/workflows/ci.linux.arm.yml
.github/workflows/ci.linux.x86_64.yml
.github/workflows/ci.macos.arm.yml
.github/workflows/ci.macos.x86_64.yml

> no unit test on push, only on pull request

[Pick][0.9 to main] | no unit test on push, only on pull request

---

thread/test/test-pool.cpp
thread/thread.h
thread/workerpool.cpp

> fix ~workerpool by using AutoContext

[Pick][0.9 to main] | fix ~workerpool by using AutoContext

---

ecosystem/simple_dom.cpp
ecosystem/simple_dom.h
ecosystem/simple_dom_impl.h
ecosystem/test/test_simple_dom.cpp

[Pick][0.8 to 0.9] | types in simple_dom

---

doc/docs/api/lock-and-synchronization.md
doc/i18n/cn/docusaurus-plugin-content-docs/current/api/lock-and-synchronization.md
examples/perf/net-perf.cpp
thread/thread.h

> net-perf server listens to multiple ports; Refine semaphore doc

[Pick][0.9 to main] | net-perf server listens to multiple ports; Refine semaphore doc

---

common/alog.cpp
common/alog.h

Fix Alog new color code condition.
Make also alog preset color for INFO level to nothing.

fix alog set color condition

---

.github/workflows/auto-pr-precise.yml

AutoPR title needs at least a newline in the end of multiline text

Fix autopr title

---

.github/workflows/auto-pr-precise.yml

> Fix autopr title (#944) (#946) (#947)

[Pick][0.9 to main] | Fix autopr title (#944) (#946) (#947) 

---

net/http/client.cpp
net/http/message.cpp
net/http/message.h

> fx http sock leaks in some error cases (#956)

[Pick][0.7 to 0.8] | fx http sock leaks in some error cases (#956) 

---

common/alog.h

enhance LOG_ERROR_RETURN and LOG_ERRNO_RETURN to optionally enforce setting values to errno

enhance LOG_ERROR_RETURN and LOG_ERRNO_RETURN 

---

common/alog.h

> enhance LOG_ERROR_RETURN and LOG_ERRNO_RETURN to optionally enforce setting values to errno (#983)

[Pick][0.8 to 0.9] | enhance LOG_ERROR_RETURN and LOG_ERRNO_RETURN to optionally enforce setting values to errno (#983) 

---

.github/workflows/ci.macos.arm.yml
common/alog.h
thread/test/test.cpp
thread/thread11.h

```
[ RUN      ] thread11.dtor
2025/09/16 14:15:32.534641|DEBUG|th=0000000000000000|test.cpp:626|Foo:ctor 000000016B2E6D14
2025/09/16 14:15:32.534808|DEBUG|th=0000000000000000|test.cpp:633|TestBody:thread_create11
2025/09/16 14:15:32.534811|DEBUG|th=0000000000000000|test.cpp:627|Foo:copy ctor 000000016B2E6CD4
2025/09/16 14:15:32.534812|DEBUG|th=0000000000000000|test.cpp:627|Foo:copy ctor 000000016B2E6C4C
2025/09/16 14:15:32.534819|DEBUG|th=0000000000000000|test.cpp:627|Foo:copy ctor 000000013F600AF8
2025/09/16 14:15:32.534820|DEBUG|th=0000000000000000|test.cpp:629|~Foo:dtor 000000016B2E6C4C
2025/09/16 14:15:32.534822|DEBUG|th=0000000000000000|test.cpp:629|~Foo:dtor 000000016B2E6CD4
2025/09/16 14:15:32.534828|DEBUG|th=0000000000000000|test.cpp:635|operator():000000013F600AF8:thread …
```

dtor for thread11
