alibaba/PhotonLibOS

net/curl.cpp
Fix compilation error for g++ (GCC) 11.3.0
#29
=> Add `#include <memory>` to curl.cpp

common/estring.h, fs/filecopy.cpp, net/utils.cpp, thread/test/test.cpp
- 将`cmake`中的`CMAKE_CXX_STANDARD`改为17和20，将会编译失败
- 本条PR修复`CMAKE_CXX_STANDARD`为17和20编译时的报错
=> Fix compile fail

common/executor/executor.cpp, common/executor/executor.h, common/executor/test/test_export_as_executor.cpp, common/expirecontainer.h, common/lockfree_queue.h, common/metric-meter/metrics.h, fs/exportfs.cpp, io/aio-wrapper.cpp, net/http/client.cpp, net/http/cookie_jar.cpp, net/http/message.cpp, net/http/message.h, net/http/test/CMakeLists.txt, net/http/test/client_function_test.cpp, net/http/test/headers_test.cpp, net/http/url.h, thread/thread.cpp, thread/thread.h, thread/workerpool.cpp
We have dig in PhotonLibOS, and now provides bug fix and features
Fix:
* `ExpireContainer<T>` insert should keep in protect by lock, in case of using in multi-vcpu condition.
* `libaio_adaptor` may stuck if `io_submit` failed, but no more libaio actions submitted.
Improves:
* `RingChannel` now has better waiting strategy, able to reduce send-recv latency.
* `Executor`, `WorkPool` are now using `RingChannel`
* `URL` add new method, able to get host path without port part
* Hook of photon thread stack allocation, to help using custom allocator
* Some GC framework needs to mark memory usage, here is a way to add such kind of mark. #150
=> Fix and improves

net/http/headers.cpp, net/http/parser.h
HTTP protocol said that the spaces before each header's value should be ignored.
Even though most HTTP client will format the header as `KEY: VALUE`, but there are still some clients who didn't add the  space. 
The previous implementation has a bug when processing `KEY:VALUE`.
=> Fix HTTP header parse for space

common/tuple-assistance.h, thread/thread11.h
Fix `thread_create11` when using photon with C++17 standard, delivering parameters by move.
=> fix compile in c++17 onward

thread/thread.cpp, thread/thread.h
经过验证：给mutex增加重试后，对多线程程序的整体性能有帮助。
使用rocksdb的db_bench做测试，关闭compaction，数据全在block cache(内存)，启动8个线程做读IO测试。通过观察OPS，比较跨线程锁的开销。
原生多线程版本：OPS = 3.7 Million ， CPU 800%
未改动的Photon协程版本，启动8个thread，配8个vcpu： OPS = 2.9 Million  ，CPU 720%
给mutex增加重试后： OPS = 3.6 Millon，CPU 800%
TODO:
1. 选取合理的retry number。在单线程和多线程程序做一些取舍。会在单线程多协程的场景稍微增加一些开销；而在多线程的场景下，相当于是用富余的CPU计算换取更高的cacheline命中率，降低锁延时。
2. 将原先代码里的一些spinlock换成新的mutex。如thread_pool里面的，当时也是为了多线程优化改的spinlock
=> mutex lock add retries

thread/workerpool.cpp, thread/workerpool.h
thread_migrate原先随机的策略有一个缺陷：当thread数量小于vcpu数量时，有一定的概率会产生多个thread堆积到某一个相同的vcpu上的情况。由于我们的thread迁移是被动的，因此一直也无法迁走。这样造成OS线程空闲，workload不均衡。
因此把random改成了round-robin。参考了没有work stealing机制的其他的库，比如cocoyaxi，用的也是rr。
-------
The original random strategy of thread_migrate has a defect: when the number of threads is less than the number of vcpus, there is a certain probability that multiple threads will be scheduled to the same vcpu. Since our thread migration is passive, it's not likely to migrate away in the future. So this causes idle OS threads and unbalanced workload.
So changed the strategy from random to round-robin. Have referred to other libraries that have no work stealing mechanism, such as cocoyaxi. They are using rr as well.
=> thread_migrate strategy changes from random to round-robin

common/executor/easyawaiter.h, common/executor/executor.cpp, common/executor/executor.h, common/executor/test/test_async.cpp, common/executor/test/test_easy.cpp, common/executor/test/test_easyexport.cpp, common/executor/test/test_std.cpp, common/test/test_objcache.cpp, include/photon/common/executor/easyawaiter.h, include/photon/thread/awaiter.h, net/http/client.cpp, thread/awaiter.h, thread/test/test.cpp, thread/workerpool.cpp, thread/workerpool.h, tools/photongdb.py
Bug fix:
* photon gdb tool script fits current register on stack layout
* fix unit test designed not fit for mutex lock that may perform thread_yield spin
* http client dialer leaks `tcp_socket_client`
Feature:
* new `AsyncAwaiter` for `Executor` and `WorkPool` implementation
=> Fix & improves

thread/thread.cpp
AArch64 CPU may using off-core timer as source of `cntvct_el0` registers, so the counter may not fit CPU working frequency. The timer frequency on Apple M1 is 24MHz, much lower than CPU working frequency, that may make `photon::now` timestamp update about every 40ms, may makes photon thread sleeps longer than it should be.
The fix uses `cntvct_el0` as a fast check whether should update time stamp, calculate with `cntfrq_el0` as timer frequency, make it able to update timestamp as it designed to.
=> aarch64 cycle count with frequency

CMake/build-from-src.cmake
=> Fix CMake sed command

doc/docs/introduction/how-to-build.md, doc/docs/introduction/how-to-integrate.md, doc/docs/introduction/photon-architecture.md, doc/docs/introduction/what-is-photon.md, doc/docs/introduction/write-first-example.md
=> ipv6 preview

net/curl.cpp
In some version of libcurl, call `curl_multi_socket_action` during callbacks will be checked and prevented by libcurl recursive check, and got a failure that not expected.
Make calling `do_action` asynchronous, make it be called from photon thread stub, will never cause this kind of situation.
=> Fix libcurl comaptible

common/lockfree_queue.h
Lockfree queue has a old bug, that cause full check return true when still has one empty slot, but return false when the queue is actually full.
This patch fixed this problem.
=> Fix lockfree queue size and full check

net/basic_socket.cpp, net/socket.h
to recv at least a number of bytes from socket stream, so as to reduce the # of syscalls
=> add a new function recv_at_least() to socket stream

.github/workflows/ci.linux.arm.yml, .github/workflows/ci.linux.x86.yml, .github/workflows/ci.macos.arm.yml, .github/workflows/ci.macos.yml, common/identity-pool.cpp, thread/thread-pool.cpp, thread/thread-pool.h
The thread-pool does not work well joining threads that running in another vCPU.
Since the pool put action is not surely ordering after joiner wake-up, when joiner and work-thread are not in same vCPU, there is a race condition that thread may going to collect and destructor routine before the returning of `join()` call.
This fix solved this problem.
=> Fix thread-pool join threads in multiple vCPUs

common/estring.h, net/http/headers.cpp, net/http/headers.h, net/http/message.cpp, net/http/message.h, net/http/status.cpp
* make ```void buf_append(char*& ptr, std::string_view sv)``` inline-able
* make some code more readable (hopefully)
* make some branching more efficient with ```? : ``` expression
* avoid ```std::to_string()```
* reimplement ```obsolete_reason()``` with efficient table lookup, instead of the big ```switch```
=> minor improvements to http

.github/workflows/ci.linux.x86.yml, CMake/build-from-src.cmake, CMakeLists.txt, common/checksum/test/CMakeLists.txt, common/test/CMakeLists.txt, examples/CMakeLists.txt, fs/extfs/test/CMakeLists.txt, fs/test/CMakeLists.txt, io/test/CMakeLists.txt, net/http/client.cpp, net/http/client.h, net/http/test/CMakeLists.txt, net/kernel_socket.cpp, net/security-context/test/CMakeLists.txt, net/socket.h, net/test/CMakeLists.txt, net/test/test-ipv6.cpp, net/utils.cpp, net/utils.h, rpc/rpc.cpp, rpc/rpc.h, rpc/test/CMakeLists.txt, thread/test/CMakeLists.txt, tools/libphoton.mri
1. RPC client now supports both v4 and v6. Don't need to create two clients any more.
2. HTTP client removes v6 temporarily. There are still a lot work to be done for HTTP to truly support IPv6 (url parse, domain resolve, single client that supports both sockets), leave this work to the future...
3. Backup errno when KernelSocketStream destruct
4. Endpoint adds a string constructor
5. CMake can build openssl and curl from source now
=> Some fixes for networking

fs/extfs/mkfs.cpp
Fix the issue of being unable to write data to ext filesystem created by user-space tools in lower version linux.
=> marking inode 1 inuse for extfs/mkfs

fs/httpfs/httpfs.cpp, net/curl.h
FIX:`preadv` in `httpfs` may return wrong read byte count if tcp connection disconnected when receiving body of response by libcurl.
`preadv` return value now only get by checking `IOVWriter` written bytes.
=> FIX httpfs preadv return wrong length of partial-read http body. 

.github/workflows/ci.linux.arm.yml, .github/workflows/ci.linux.x86.yml, .github/workflows/ci.macos.arm.yml, .github/workflows/ci.macos.yml, CMake/build-from-src.cmake, io/iouring-wrapper.cpp, thread/test/CMakeLists.txt, thread/test/test-multi-vcpu-locking.cpp
Fix https://github.com/alibaba/PhotonLibOS/issues/261
=> fix io_uring cancel_wait

thread/thread.cpp
Mutex locking needs to have memory-order acquire semantics. Imagine two threads incrementing a counter, protected by a mutex:
Preconditions:
* Mutex atomic `owner = nullptr`
* Non-atomic variable `X = 0`
Each thread:
1. `mutex::try_lock` successfully performs [`owner.compare_exchange_strong(self, memory_order_release)`](url). This only guarantees that any **preceding** reads and writes are not reordered after this one.
2. `X = X + 1`. This is not an atomic variable and therefore depends on the memory ordering of `owner` to synchronize reads and writes.
3. `mutex::unlock` calls `owner.store(nullptr)` which has `seq` ordering. This guarantees no preceding or subsequent reads or writes will be reordered.
But because the CAS uses `release` memory ordering, other threads can reorder 2 before 1 …
=> Use acquire-release memory order for mutex::try_lock

fs/httpfs/httpfs.cpp, fs/httpfs/httpfs_v2.cpp
The current HTTP header has a bug of wrong key value order.
This is the POC. It will print `v` first, and then `k`, which is obviously wrong.
```c++ 
#include <iostream>
#include <string>
#include <map>
#include <string>
#include <cstdarg>
std::map<std::string, std::string> common_header;
void add_header(va_list args) {
common_header[va_arg(args, const char*)] = va_arg(args, const char*);
}
void f(int a, ...) {
va_list args;
va_start(args, a);
add_header(args);
va_end(args);
}
int main() {
f(1, "k", "v");
for (auto& i: common_header) {
std::cout << i.first << std::endl;
std::cout << i.second << std::endl;
}
}
```
=> Fix the va_args order of http header

thread/thread.cpp
The previous SCOPED_MEMBER_LOCK will visit member address even if the object itself is nullptr.
This behavior will cause an runtime error in the UndefinedBehaviorSanitizer check (https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html), although the compiler didn't regard it as a warning.
Removed SCOPED_MEMBER_LOCK, luckily this is the only usage in the whole project.
=> Mute an UBSan check error for SCOPED_LOCK macro

CMakeLists.txt, io/aio-wrapper.cpp, io/epoll.cpp, io/fstack-dpdk.cpp, io/iouring-wrapper.cpp, io/kqueue.cpp, io/reset_handle.cpp, io/reset_handle.h, io/signal.cpp, io/test/CMakeLists.txt, io/test/test-fork.cpp, net/curl.cpp, photon.cpp
In photon context, event engine based module need reset after fork, if exec will not be called after fork.
This is implicitly done by pthread_atfork hook.
=> support reset photon at fork

common/simple_dom.cpp, common/simple_dom.h, common/simple_dom_impl.h, common/stream.cpp, common/stream.h, common/test/test_simple_dom.cpp, include/photon/common/simple_dom.h
with examples and tests to show the usage
=> Interface design of simple unified access to json, xml, yaml, ini, etc. 

examples/rpc/server.h, net/basic_socket.cpp, net/socket.h, rpc/rpc.cpp, rpc/rpc.h, rpc/test/test-rpc-message.cpp, rpc/test/test.cpp
rpc支持graceful shutdown，即等待客户端主动关闭链接。
配合socket server现有的terminate（即只关listen fd，阻止建立新链接；不关active connection），可以用如下代码实现优雅关闭：
```c++
socket_server->terminate();
delete socket_server;
rpc_skeletion->shutdown(true);
delete rpc_skeletion;
```
=> rpc graceful shutdown

CMakeLists.txt, fs/extfs/extfs.cpp, fs/extfs/extfs.h, fs/extfs/extfs_io.cpp, fs/extfs/mkfs.cpp, fs/extfs/test/test.cpp, fs/subfs.cpp
Extfs and subfs implement IFileSystemXAttr interface to support xattr.
Add xattr test case for extfs.
=> fs: support xattr for extfs and subfs

CMakeLists.txt, io/epoll-ng.cpp, io/fd-events.h, photon.cpp, photon.h
A new epoll event engine implementation (EPOLL_NG) which use epoll groups to manage read/write events.
This is much simpler and use no on-heap memory allocation, with better performance, as mentioned in #268 
Edge-trigger related feature will be implemented in future.
New engine shows 3%~5% throughput/QPS improvement by `net-perf` test.
=> New epoll event engine implemention that may be more effecient

CMakeLists.txt
Rename ${LIBE2FS_INCLUDE_DIRS} to ${E2FS_INCLUDE_DIRS}
which is defined in https://github.com/alibaba/PhotonLibOS/blob/release/0.7/CMake/Finde2fs.cmake
=> fix e2fs include dir name

net/http/client.cpp, net/http/client.h, net/http/test/CMakeLists.txt, net/http/test/client_tls_test.cpp
Support HTTP client to use specified certificates. It's necessary when two-way authentication is enabled (the server will verify the client's identity) on the HTTP server.
=> [feat] http client with cert

fs/fuse_adaptor.cpp, net/http/client.cpp, net/http/test/client_function_test.cpp, net/kernel_socket.cpp, net/test/test.cpp, net/utils.cpp, net/utils.h, thread/list.h
1. Support ipv6 in http client.
- refactor KernelSocketClient by removing socket_family in KernelSocketClient.
- apply dns load balance in DefaultResolver.
- fix bug in DefaultResolver when timeout happen.
2. Add big writes/uid/gid/du support to FUSE
- In Fuse 2.x, without big writes, write io size is limited to 4k. Turing it on can enlarge write io size to 128K at maximum.
- Support du by adding st_blocks to xmp_getattr result.
- Add default uid/gid to xmp_getattr to avoid permission problems.
=> Support ipv6 in http client

common/expirecontainer.cpp, common/expirecontainer.h, common/test/test_objcache.cpp
ObjectCache specialization for intrusive_list value-type.
Do not need to create a intrusive_list(which is only a node pointer) as ObjectCache value in creator. Store the list as a member of ObjectCache item.
=> ObjectCache with intrusive_list specialization

CMake/build-from-src.cmake, net/kernel_socket.cpp, net/socket.h
When errors happened, we often get an empty `Endpoint` with an empty `IPAddr`, but we'll usually not reset zero value to its `port`.
An empty IP is enough to indicate it's `undefined`, and makes it more convenient to use.
Another option is to change the condition from AND to OR.
=> Re-define an undefined endpoint

include/photon/thread/stack-allocator.h, thread/stack-allocator.cpp, thread/stack-allocator.h, thread/test/CMakeLists.txt, thread/test/test-pooled-stack-allocator.cpp, thread/thread-pool.cpp, thread/thread-pool.h, tools/export-header.py
In typical scenarios, we utilize photon::thread_pool primarily due to the efficiency gains from reusing existing photon threads rather than creating new ones.
From my observation, the most resource-intensive aspect of creating a photon thread is the allocation of its stack memory. It is notably more straightforward and offers better performance to reuse pre-allocated stack memory directly compared to reusing it through a thread pool mechanism.
Although the current `IOAlloc` toolset isn't compatible with stack allocation operations that cannot rely on photon thread utilities, I have developed a thread-local stack pool, enabling the practical reuse of already allocated stacks.
In our tests, the `photon::WorkPool` utilizing a pooled stack allocator outperforms the version using a traditional …
=> `PooledStackAllocator` helps improve performance of thread creating

.github/workflows/ci.linux.x86.yml, io/iouring-wrapper.cpp
> io_uring accounts memory it needs under the rlimit memlocked option, which
> can be quite low on some setups (64K). The default is usually enough for
> most use cases, but bigger rings or things like registered buffers deplete
> it quickly. This affects 5.11 and earlier, new kernels are less dependent
> on RLIMIT_MEMLOCK as it is only used for registering buffers.
=> iouring: remove RLIMIT_MEMLOCK check for new kernel

fs/httpfs/httpfs_v2.cpp
In httpfs V2, give it a client with proxy does not makes all file access going with proxy.
Every request will be reset during fetching requests. But`op.set_enable_proxy()` only marks it using or not using proxy.
Do or do not generate request follows proxy standard is only decided by the third argument in request reset  operation (which has default value `false`)
Fix it by setting correct argument of `reset` call.
=> Fix HTTPFSv2 using proxy

.gitignore, io/aio-wrapper.cpp, io/aio-wrapper.h, photon.cpp, photon.h, thread/test/test-pooled-stack-allocator.cpp
This Pull Request proposes enhancements to the photon::init initialization procedure by introducing the ability to set crucial options directly within or prior to its invocation. To improve user convenience and configurability, the following three new options have been added:
1. Libaio Context Size Configuration: Allows users to specify the size of the libaio context.
2. Pooled Stack Allocator Enablement: Provides an option to utilize a pooled stack allocator for improved memory management.
3. Thread Pool Bypass: Introduces a mechanism to bypass the thread pool when necessary.
In line with this enhancement, the testing suite for the pooled-stack-allocator now utilizes the extended photon::init API, taking advantage of these newly introduced options as part of its setup process. This …
=> Add extra options in `photon::init`

common/iovector.h, net/socket.h
In issue #350 
Shows new version GCC performs more check for old GNU extensions, and treats union as non-POD member in struct layout.
Here some fixes for them, tested worked in GCC 13.2 and fits the requirements of C++ standard:
1. Use flex array instead of deprecated zero-sized array which causes warning.
2. Prevent inherent to a struct with flex-array.
3. Add attribute for union in `IPAddr`, make `IPAddr` struct able to be packed
=> Fix IPAddress packed layout and iovector flex array

fs/httpfs/httpfs_v2.cpp
This pull request addresses an issue with the ioctl set header functionality in `httpfs_v2`. Currently, `httpfs_v2` treats ioctl headers differently than httpfs, by appending records instead of handling them as a key-value map.
The proposed changes aim to align the behavior of httpfs_v2 with httpfs, ensuring that ioctl headers are treated consistently across both implementations. This will improve compatibility and make it easier for developers to work with these file systems.
=> FIX httpfs_v2 common header for file able to replace by ioctl

common/alog.cpp, common/alog.h, thread/thread.cpp
This pull request introduces a change to the ALog Prologue module. The modification made is to keep only the last part of the source path, specifically the filename, while utilizing microsecond timestamps.
Microsecond timestamps shares photon thread timestamp `photon::now`.
=> ALog Prologue now keeps only last part of source path (filename), using us timestamps

common/alog.h
Fix issue in the alog prologue where the filename portion was mistakenly truncated, losing the last character.
=> Fix prologue file field length

common/alog.h
To make named value with char array reference acts like printing string, last fix build a temporary ALogString for value.
Value field of `NamedValue<T>` is a `CopyOrRef<T>` type, makes small object copy and big-enough type a reference.
And ALogString takes 16 bytes as a big structure, will take reference type.
that makes `make_named_value` to a char array used a reference to on-stack temporary object, which is a UB for C++, and may cause segfault with optimization in GCC 11.4.
This pull request fix it by only cast to char pointer, and let type conversion goes in later stage in logging, or said formatting step.
Though, `const NamedValue<ALogString>&` output overloading is useless, so remove it.
=> Fix: make_named_tuple maked ref to temporary alogstring

thread/test/test.cpp, thread/thread.cpp, thread/thread.h
This pull request improves the synchronization components based on `waitq` by adding support for interruption using `thread_interrupt`. The semaphore component, which was previously unable to be interrupted, is now included in this enhancement.
Interruption of a running photon thread can be beneficial in specific situations, such as during the graceful shutdown of a process. This update enables more efficient and controlled termination of threads, resulting in improved system reliability and performance.
Additionally, the internal photon thread interruption errno used by `waitq` has been changed to -1 by default. As a result, users can now utilize all generic error numbers to interrupt synchronization components.
=> Semaphore now able to be interrupted

net/kernel_socket.cpp, net/test/test-ipv6.cpp
The `undefined` has caused many troubles. Shall we use the rest 16bits padding of Endpoint as a new flag to indicate it's undefined?  @lihuiba @Coldwings 
Extra alignment are no longer needed as well.
=> Fix endpoint undefined situation

io/epoll.cpp, io/fd-events.h, net/test/test.cpp, net/utils.h
So that all invocations to wait_for_fd_xxx() will benefit from it, especially the one in cascading engine.
=> Realize true one-shot semantics for epoll with EPOLLONESHOT

io/epoll.cpp
by redefining semantics of rm_interests() with ONE_SHOT flag
=> make epoll oneshot working for cascading engine

io/epoll.cpp
and improve logic in add_interests() and rm_interests()
=> add judgement for conflicted ONE_SHOT flag in add_interests()

common/alog.h, common/retval.h, common/test/test.cpp, include/photon/common/retval.h
so as to avoid some bugs:
* unintentionally change the global errno by some function calls (e.g. printf or LOG_XXXX) in the error handling path,  causing misunderstanding about the error
* return an error but forget to set errno, causing incorrect handling of the error
In addition, ```retval<T>``` makes the error number returned in register, more efficient than the global thread-local ```errno``` variable.
=> retval<T> to return a value and an error number at the same time

net/curl.h
#435 mentioned some deprecated curl option in net/curl.h
`CURLOPT_DNS_USE_GLOBAL_CACHE` and `CURLOPT_PUT` are deprecated in libcurl 7.11 7.12 version, which is toooo old that photon may never considering support them.
`CURLOPT_PUT` is as same as `CURLOPT_UPLOAD`, and is already set in code.
`CURLOPT_DNS_USE_GLOBAL_CACHE` become deprecated, should set using `curl_share` API, but here in code disabled sharing global dns cache, which is default action in libcurl, so it can be simply removed.
=> Remove some outdated libcurl option usage in curl wrapper header

CMake/build-from-src.cmake
liburing's makefile surprisingly used `?=` instead of `+=`  ...  🤦
https://github.com/axboe/liburing/blob/f1dfb94bdaf1de14281030e28dd64f4d23d615a3/src/Makefile#L13C8-L13C9
=> zlib and uring source build didn't have -O3

rpc/test/test-ooo.cpp, thread/test/test.cpp, thread/thread.cpp, thread/timer.h
Add a extra page on the top-end of photon stack and set to `mprotect` `PROT_NONE`.
When code access this page, will through a segment fault immediately, so user will notice that there might be stack overflow.
=> Add mprotect for the top-end of photon stack

io/epoll.cpp
- Continuously calling epoll_wait 0 (when scheduler is idle) will not incurease CPU usage at all
- epoll_wait 0 only consumes 1 us, even better than io_uring's 5 us
=> epoll_wait allows to wait 0ms, instead of the previous 1ms

net/utils.cpp
call ipaddr->delete_all() if ip.undefined()
=> fix dns resolver discard_cache

net/pooled_socket.cpp
In release() of TCPSocketPool, the call to stream_alive() modifies errno even if it succeeds. So restore and reset errno if stream_alive() success.
=> restore errno when release success in pooled socket

.github/workflows/ci.linux.x86-64.yml, io/epoll-ng.cpp, net/http/test/server_function_test.cpp, photon.cpp, test/ci-tools.cpp
`epoll-ng` `wait_for_fd` with event 0 (no event) should return immediately.
=> FIX: epoll-ng wait for fd with event 0

.github/workflows/ci.linux.arm.yml, .github/workflows/ci.linux.x86.yml, .github/workflows/ci.macos.arm.yml, common/lockfree_queue.h
FIX:
now mpmcqueue able to be sure not return failure pop from non-empty queue or push into non-full queue.
=> FIX: lockfree MPMC queue should not fail to pop/push when queue is not empty/full

fs/async_filesystem.cpp, fs/exportfs.cpp, fs/test/CMakeLists.txt, fs/test/mock.h, fs/test/test_exportfs.cpp
When using an exported fs，ExportPerformer put called function to a SPSCRingQueue and wait to be waked when finished.   Related code is below:
```
R perform(IF* _if, Func func, ARGS...args)
{
AsyncWaiter<R> w;
(_if->*func)(args..., w.done(), _timeout);
return w.wait();
}
```
In situations where `_if->*func` is unimplemented, the function ` _if->*func` will call `w.done()` directly, which cause a dead lock beacuse it try to lock a locked mutex.
This pr do the following things: 
1. fix the dead lock bug by moving the lock action in ExportPerformer from its construciton function to wait() function.
2. Add an unittest `ExportFS.no_xattr_sync` to verify this dead lock behavior.
3. Implement `fallocate` fuction of ExportAsAsyncFile because this method is widely used in fuse.
Besides, I marked …
=> fix dead lock in ExportPerformer

common/lockfree_queue.h, common/test/test_lockfree.cpp
In issue #446 mentioned that mpmc batch queue may meet failure on aarch64 platform.
Here is a patch for this problem, and some performance improvement.
=> fix batch mpmc queue

.github/workflows/auto-pr.yml, .github/workflows/ci.linux.arm.yml, .github/workflows/ci.linux.x86-64.yml, .github/workflows/ci.macos.arm.yml, .github/workflows/ci.macos.x86.yml, common/iovector.h, common/test/test.cpp, rpc/rpc.cpp, test/ci-tools.cpp, thread/test/test-pool.cpp
Fix code that prevent warnings when compile in gcc 12.
CI UT actions go CMake config phase with same gcc version, so all tests binary are used to compiled by gcc850 only. Previous CI configure use self hosted compile machine with no parallels, so last test group have to wait till all compile tasks are finished. That will always spent about 26min. for UT.
All paralleled compile and tests have no dependencies between jobs, with base image that all dependencies are pre-installed, each round of compile + test runs about 18min. All test jobs may able to be finished in less than 20min.
=> CI with fully parallel jobs

thread/stack-allocator.cpp
When slog is empty, should alloc memory with size fit in slot.
=> Fix on stack allocator

common/rcuptr.h, common/test/CMakeLists.txt, common/test/perf_rcuptr.cpp, include/photon/common/rcuptr.h
A simple RCUPtr<T> implementation in photon environment, takes photon thread as reader/writer, based on rcu-qsbr.
RCU is a simple synchronize unit for concurrent read and light write.
RCU means Read-Copy-Update, Concurrent readers takes nearly no extra costs. only writer have to copy & update object and atomic switch pointer. Expired objects can always be free after grace period.
RCUPtr has a few common limits. IT IS NOT FOR ALL USERS.
=> RCUPtr for photon thread environment

common/lockfree_queue.h, common/objectcachev2.h, common/test/CMakeLists.txt, common/test/perf_objcache.cpp, common/test/test_objcache.cpp, include/photon/common/objectcachev2.h
A simpler but effective object cache implementation.
`ObjectCacheV2` shows better performance compare to `ObjectCache`, with several
improvements:
1. Less lock in both read and write.
2. Object destruction always goes in background photon thread called reclaimer.
3. Self adjustable timeout for reclaimer. No needs to set cycler timer.
4. New `update` API, able to immediately substitute objects.
5. `ObjectCacheV2` no longer support acquire/release API.
It should work as `ObjectCache` in code do not depends on acquire/release API.
=> objcachev2

common/lockfree_queue.h
`RingChannel::send` may have chance that`idler.load()` happens before the `push` work done.
The acquire flags at load only make sured that load after `idler.load()` have to be happened after `idler.load()`, and last store action in `push(x)` keeps only sequence of store order only. Make it in seq_cst order to make sure load action must after push done.
=> Add mfence for ringchannel send

CMakeLists.txt, fs/httpfs/httpfs_v2.cpp, net/kernel_socket.cpp, net/security-context/tls-stream.cpp
=> openssl not use locking after 1.1.0

common/enumerable.h, common/objectcachev2.h, common/ring.cpp, common/test/CMakeLists.txt, common/test/perf_objcache.cpp
=> Some modify and fix in ObjectCacheV2

io/epoll-ng.cpp, rpc/test/test.cpp
RpcTest.shutdown case with epoll-ng io engine has chance failing.
Checked all code, found two problems:
1. EpollNG is possible still got event just after removed watching, makes wake-up notify context not available when waiting thread canceled. Fix by force notify after canceling.
2. The unit test required background thread have to be execute first, still, during calling `sk->shutdown`, it have chance to yield thread, makes main thread continue and cause object sk double free. Make it only delete once, and wait for background thread finish by thread join.
=> Fix on epoll-ng when testing in RpcTest shutdown

common/alog.cpp, common/test/test_alog.cpp
DEC(0) via ALOG shows strange "-0" result, since conditions for positive integer missed `x.svalue() == 0` condition.
Fix and add test for that situation
=> Fix alog DEC(0) shows -0

common/test/test.cpp, common/unordered_inline_set.h
A hash table with open addressing, i.e. collision is resolved by probing, or searching through alternative locations in the array. 
This design avoids allocation and deallocation during insertion and deletion, except rehashing.
it also features the ability to extract (move out) a stored element itself, without involving a "handle".
This is only an initial version that need further test and polish.
=> unordered_inline_set

io/epoll.cpp, io/kqueue.cpp, net/pooled_socket.cpp
=> Fix/sockpool wait_for_fd 0.8

thread/std-compat.h
The standard lib provides such syntax:
```std::thread::id tid;```
For photon_std, it is `photon:thread*`, and probably not init to 0, so caused a CI failure in RocksDB.
This PR makes it follow the standard.
=> Fix photon_std::thread::id default constructor

.github/workflows/images/base/build_push.yml, .github/workflows/images/fstack/Dockerfile, .github/workflows/images/fstack/build_push.yml
把CI镜像的构建流程和Dockerfile脚本从个人仓库移到主仓库。
-----
Move the CI image build process and Dockerfile script from the personal repository to the main repository.
=> CI add build_push actions

.github/workflows/ci.linux.arm.yml, CMake/Finduring.cmake, CMake/build-from-src.cmake, common/test/test_objcache.cpp, fs/test/test_exportfs.cpp, io/iouring-wrapper.cpp, thread/test/test-pool.cpp
It's been a long time we didn't run `DEBUG` build and verify `PHOTON_BUILD_DEPENDENCIES`.
So some warnings appeared.
Add it back in arm CI
=> Re-add PHOTON_BUILD_DEPENDENCIES in x86 CI workflow

net/http/client.cpp, net/security-context/tls-stream.cpp, net/security-context/tls-stream.h
Also makes http client verify X509 certs by default when requesting HTTPS server.
=> TLSContext now able to set X509 cert verify

thread/thread.cpp
make cross-vcpu interrupt latency lower, by more frequent checking of standby queue.
=> make cross-vcpu interrupt latency lower

CMakeLists.txt
copy include & libs to install directory
=> Add install option for cmake

common/expirecontainer.cpp, common/expirecontainer.h, common/test/test_objcache.cpp, rpc/rpc.cpp
Make ObjectCache able to move-out managed object when releasing.
It will wait till all shared acquirements are released, and then return object back who is trying to move out.
=> Add moveout feature for ObjectCache

.github/workflows/auto-pr-new.yml
The old auto-pr simply create PR between branches.
This one will check push event, picks all commits in that push event and then make PR, so each auto-pr creates new branch contains changes only in merged PR.
=> Another auto-pr create one pr for each merge

.github/workflows/auto-pr-autodelete.yml
Since new auto-pr will create temporary branch to pick commits for creating PR,
after PR merged, should automatically delete related auto-pr branch.
=> auto delete auto-pr branch which is merged

common/estring.cpp, common/estring.h, common/string-keyed.h, common/test/test.cpp
comparison is 4+ times faster on MBP M1:
```
[ RUN      ] tolowerupper.perf_strncasecmp
[       OK ] tolowerupper.perf_strncasecmp (3270 ms)
[ RUN      ] tolowerupper.perf_photon__stricmp
[       OK ] tolowerupper.perf_photon__stricmp (777 ms)
```
=> fast case conversion and comparison

thread/thread.cpp, thread/thread.h
(1) add an option for in-order resume of threads (by default not); 
(2) avoid thundering herd of threads whose needs are not met;
=> semaphore plus

common/estring.h, net/http/client.cpp, net/http/server.cpp
This implementation tries to avoid memory allocation and memcpy. It does so only when necessary.
=> extract_c_str() for estring_view

CMakeLists.txt
Issue version: found only 19 occurrence of "overriden"
Fixed version: found 100 occurrence of "overriden"
=> enforce linking of ci-tools

rpc/rpc.h
there is two `new_skeleton` overloads, one with
`new_skeleton(uint32_t pool_size = 128)`
and another one is deprecated,
`new_skeleton(bool, int)`
when user calling with a integer parameter, such as
`new_skeleton(32)`
since c++ allows explicit cast from int to bool, both of those overloads are able to be called, become ambiguous calling.
remove the default parameter value of deprecated one, when user trying goes with only one parameter, it will always call the first implementation.
=> Make `new_skeleton` with one argument able to be call

.github/workflows/ci.linux.arm.yml, .github/workflows/ci.macos.x86_64.yml, CMakeLists.txt, common/checksum/crc32_iscsi_00.asm, common/checksum/crc32_iscsi_crc_ext.S, common/checksum/crc32c.cpp, common/checksum/crc64_ecma_refl_by8.asm, common/checksum/crc64_ecma_refl_pmull.S, common/checksum/crc64ecma.cpp
Have modified the source code slightly to minimize the number of files included.
=> Integrate HW implementations from Intel & Arm for both CRC32C & CRC64-ECMA

common/test/test_throttle.cpp
Have re-run the CI many times. No more core dumps now.
=> Fix test_throttle CI

net/http/body.cpp
HTTP Body read stream used deal with io-vector with `IOVector`, which is `IOVectorEntity<32,4>`, has only 28 slots for iovec array.
Using `SmartCloneIOV` with `iovector_view` can accept iovec array with any length.
=> HTTP Body read should able to accept long iovecs

net/utils.cpp
delete_all() and recycle() is not atomic; and there may be read-write race as well.
=> fix potential race condition in DefaultResolver when discard_cache()

CMakeLists.txt, common/checksum/crc.cpp, common/checksum/crc32c.h, common/checksum/crc64ecma.h, common/checksum/test/test_checksum.cpp, common/string_view.h
|     | 128KB Data (Cached) | 1GB Data (Non-Cached)|
| -------- | ------- | ------- |
| AVX512-cpp  | 48.47 GB/s    | 13.88 GB/s|
| SSE-cpp         | 25.86 GB/s    |12.23 GB/s|
| SSE-asm                | 25.81 GB/s    |11.99 GB/s|
=> crc64_with_avx512

doc/docs/introduction/how-to-build.md, fs/extfs/extfs.cpp, fs/extfs/test/test.cpp
some changes:
1. invalid memory address access when create extfs failed
2. add UT
3. update doc
=> [fix.] segfault when create_extfs() failed.

net/http/headers.cpp, net/http/url.cpp, net/http/url.h
- Change HeaderAssistant to dictionary order sorting, as some scenarios require traversing headers in dictionary order, such as OSS signature v4.
- Add a parameter to url_escape, as sometimes / does not need to be escaped.
=> minor update for http url and headers

fs/extfs/extfs.cpp, fs/extfs/test/test.cpp
Implement the method 'ExtFileSystem::get_underlay_object()' to return its underlay file
=> [feat.] implement extfs::get_underlay_object()

common/checksum/test/crc32_iscsi_00.asm, common/checksum/test/crc32_iscsi_crc_ext.S, common/checksum/test/crc64_ecma_refl_by8.asm, common/checksum/test/crc64_ecma_refl_pmull.S
The "weak" declarations in common/checksum/test/*.asm are no longer useful, and they sometimes cause compilation issues when binutils or nasm are not new enough.
=> remove weak

net/http/message.cpp, net/http/server.cpp
These lines both cause a warning on the following line, which aborts the build due to -Werror:
`error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]`
This happens even though I am building with Clang (19.1.6).
Making them `const` resolves the error.
=> fix: -Wvla-cxx-extension errors

CMakeLists.txt, io/iouring-wrapper.cpp, thread/thread.cpp, tools/photongdb.py, tools/ppstack
Using exported functions to fetch variables that debug tools needs, so that using libphoton.so without source can also using gdb debug tool.
Add ASAN fiber API hooks. Clang && GCC address sanitizer can now correctly recognize photon thread stacks.
=> Enhance debug tools

.github/workflows/ci.macos.arm.yml, .github/workflows/ci.macos.x86_64.yml, examples/perf/net-perf.cpp, examples/rpc/client.cpp, examples/rpc/client.h, examples/rpc/client_main.cpp, examples/rpc/server.cpp, examples/rpc/server_main.cpp, rpc/rpc.cpp, rpc/rpc.h
1. Able to change RPC socket type
2. Improve doc of rpc.h
3. RPC example now support echo_perf option, able to run performance test loop.
4. Fix example bind to localhost bug, cannot be tested on different hosts.
=> RPC: Able to change socket type; Improve doc;  Example support echo perf test

rpc/rpc.cpp
> Fix on RPC async_serve accessing count after context call (#763)
=> [Pick][0.7 to 0.8] | Fix on RPC async_serve accessing count after context call (#763)

rpc/rpc.cpp
> Fix on RPC async_serve accessing count after context call (#763) (#764)
=> [Pick][0.8 to main] | Fix on RPC async_serve accessing count after context call (#763) (#764)

net/kernel_socket.cpp
TCPSocket before release/0.8 always set TCP_NODELAY by default, there fore http client/server and tcp client/server are always goes with TCP_NODELAY.
Somehow, last year, a socket refactoring changed the behavior. That leads to long 40ms latency kept happen in TCP related io.
Fix it by changing default initialize parameters.
Thanks @f0cii helps found and fix this problem.
Co-authored-by: f0cii <2201441955@qq.com>
=> Set TCP_NODELAY by default

net/kernel_socket.cpp
> Set TCP_NODELAY by default (#767)
Fix TCPServer 40ms delay.
Thanks @f0cii helps found and fix this problem.
Co-authored-by: f0cii <2201441955@qq.com>
=> [Pick][0.8 to main] | Set TCP_NODELAY by default (#767)

cache/pool_store.h
Fix compilation errors encountered in some environment
```bash
xxxxx/build/_deps/photon-src/include/photon/cache/pool_store.h:266:21: error: field ‘src_name_’ has incomplete type ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’}
266 |         std::string src_name_;
|           
```
=> fix include in pool_store.h

common/estring.h, common/test/test.cpp, net/http/test/client_function_test.cpp
1. Function _istarts_with_ in estring_view isn't functioning correctly. Fix it by adding substr.
2. Add more unittest for estring_view and url utils.
=> fix istarts_with bug in estring_view

common/stream.cpp, ecosystem/simple_dom.cpp, ecosystem/simple_dom.h, ecosystem/simple_dom_impl.h, ecosystem/test/test_simple_dom.cpp
make simple_dom preseving the nodes' order of the document by creating and sorting an index, instead of the nodes themselves.
=> make simple_dom preseving the nodes' order of the document

common/stream.cpp, ecosystem/simple_dom.cpp, ecosystem/simple_dom.h, ecosystem/simple_dom_impl.h, ecosystem/test/test_simple_dom.cpp
> make simple dom preseving the nodes' order of the document, by
creating and sorting an index, instead of the nodes themselves.
=> [Pick][0.9 to main] | make simple dom preseving the nodes' order of the document, by creating and sorting an index, instead of the nodes themselves.

CMakeLists.txt, doc/docs/api/env.md
> CMake: Some gcc does not recognize -faligned-new. It's only for g++
=> [Pick][0.9 to main] | CMake: Some gcc does not recognize -faligned-new. It's only for g++

photon.cpp
Photon environment finish hook should clear after fired.
When photon init and finish execute twice in same vcpu, the second round of photon fini will also fires hook functions in first round, may cause problems.
Fixed by clear the thread-local vector after fired.
=> fini_hook should clear after executed

fs/cache/test/cache_test.cpp, io/fd-events.h, io/iouring-wrapper.cpp, io/iouring-wrapper.h, net/vdma/shm.cpp
It is observed that, when using io_uring to interact with libfuse, it's more performant to submit I/O requests to ```fuse_dev_fd``` without blocking on io_uring. So we need to use cascading engine to issue I/O and block on eventfd and epoll master engine.
=> io_uring cascading engine supports for I/O

fs/fuse_adaptor/fuse_adaptor.cpp, fs/fuse_adaptor/session_loop.cpp, fs/fuse_adaptor/session_loop.h
This PR introduces a new mode that leverages the io_uring cascading event engine to submit read requests to FUSE devices, with a dedicated coroutine using the master event engine for result harvesting
=> fuse-adptor: Implement iouring io mode for session loop

common/estring.h, common/test/test.cpp
The trim function previously used 'char' type for comparing characters,
which causes sign-extension issues when character values are in the range
128~255.
Change to use 'unsigned char' ensures correct comparison and fixes the bug.
=> Fix incorrect char usage in estring trim function

examples/perf/net-perf.cpp
> Fix net-perf example if work_pool is nullptr
=> [Pick][0.9 to main] | Fix net-perf example if work_pool is nullptr

common/estring.h, common/test/test.cpp
> Fix incorrect char usage in estring trim function
The trim function previously used 'char' type for comparing characters,
which causes sign-extension issues when character values are in the range
128~255.
Change to use 'unsigned char' ensures correct comparison and fixes the bug.
=> [Pick][0.9 to main] | Fix incorrect char usage in estring trim function

net/curl.h
> Force libcurl using http/1.1 since photon wrapper does not support using http/2
=> [Pick][0.7 to 0.8] | Force libcurl using http/1.1 since photon wrapper does not support using http/2

.github/workflows/images/base/Dockerfile
For some reason, newer almalinux-8 image with libcurl breaks down all libcurl-wrapper related tests.
Make libcurl and base image using certain version that used to be ok for tests.
=> UT image use specific base image version

net/curl.h
> Force libcurl using http/1.1 since photon wrapper does not support using http/2
=> [Pick][0.8 to 0.9] | Force libcurl using http/1.1 since photon wrapper does not support using http/2

net/curl.h
> Force libcurl using http/1.1 since photon wrapper does not support using http/2
=> [Pick][0.9 to main] | Force libcurl using http/1.1 since photon wrapper does not support using http/2

common/lockfree_queue.h
> FIX: lockfree BatchMPMCQueue on aarch64
=> [Pick][0.8 to 0.9] | FIX: lockfree BatchMPMCQueue on aarch64

common/lockfree_queue.h
> FIX: lockfree BatchMPMCQueue on aarch64
=> [Pick][0.9 to main] | FIX: lockfree BatchMPMCQueue on aarch64

thread/workerpool.cpp, thread/workerpool.h
> workpool refine: making it completely usable in non-photon env
by converting mutex to spinlock
=> [Pick][0.9 to main] | workpool refine: making it completely usable in non-photon env by converting mutex to spinlock

net/http/client.cpp
> ensure at_photon_fini executed in PooledDialer when photon init and finish twice
=> [Pick][0.9 to main] | ensure at_photon_fini executed in PooledDialer when photon init and finish twice

common/alog.h, common/test/test_alog.cpp
To always log something, simple define a macro ```ALWAYS_LOGGED``` that expands to a tuple of items to log.
```cpp
using photon::get_vcpu;
#define ALWAYS_LOGGED std::make_tuple(VALUE(get_vcpu()), ' ', ALogStringL( \
"{this is an always logged item "), 7, ALogStringL("wahaha}"), ' ')
TEST(ALog, always_log) {
log_output = &log_output_test;
LOG_DEBUG(32, "   ",
DEC(2345678).comma(true).width(10),
DEC(678).comma(true).width(10),
DEC(8).comma(true).width(10),
DEC(5678).comma(true).width(10));
puts(_log_buf);
memset((char*)log_output_test.log_start() + 12, 'x', 16);
EXPECT_EQ(log_output_test.log_start(), string(
"[get_vcpu()=xxxxxxxxxxxxxxxx] {this is an always logged item 7wahaha} 32    2,345,678       678         8     5,678"));
}
#undef ALWAYS_LOGGED
```
=> alog supports for always logged item(s)

common/lockfree_queue.h, common/test/test_lockfree.cpp
* Add FlexLockfreeMPMC/MPMCBatch/SPSCRingQueue, able to set size when create or init.
* Remove unused code blocks.
* Calculate ringqueue size with builtin functions
* Queue size makes always bigger than it required.
=> LockfreeQueue with flexible size.

common/utility.h
issue: #909 
`likely` and `unlikey` is also defined in dpdk or other project. Declaration conflict occur when photonlibs and dpdk are compiled together.
=> [fix #909] fix compile error

common/utility.h
> [fix #909] fix compile error
`likely' and `unlikey' is also defined in dpdk or other project.
Declaration conflict occur when photonlibs and dpdk are compiled
together.
Signed-off-by: ivanallen <ivan_allen@163.com>
=> [Pick][0.8 to 0.9] | [fix #909] fix compile error

common/lockfree_queue.h
In GCC14 it will check posix_memalign return value.
Make FlexQueue check return value instead of checking pointer
=> FIX compile in gcc14

thread/thread.cpp
> Fix X86 linux asan start call
=> [Pick][0.8 to 0.9] | Fix X86 linux asan start call

thread/thread.cpp
> Fix X86 linux asan start call
=> [Pick][0.9 to main] | Fix X86 linux asan start call

thread/thread.cpp
As mentioned in #919 , the flame-graph generated by `perf` with call-graph fp (default call-graph capture mode) and `-fno-omit-frame-pointer` may capture weird stack bottom which contains thread pointer as frame pointer.
Turns out that `_photon_thread_stub` using register `rbp` as thread pointer parameter, may break the assumption of frame pointer on stack.
Fix it by make both stack `rbp` and `rbp` register to zero, now stack bottom can be clear and simple when compiling with `-fno-omit-frame-pointer`
=> Prettify thread stack bottom fp for perf unwind with fp

thread/thread.cpp
> Fix ASAN access stack after vstack destructed (#949)
=> [Pick][0.8 to 0.9] | Fix ASAN access stack after vstack destructed (#949) 

common/objectcachev2.h
> FIX: objcachev2 should not use spinlock for create or erase (#955) (#957)
=> [Pick][0.9 to main] | FIX: objcachev2 should not use spinlock for create or erase (#955) (#957) 

thread/workerpool.cpp
In heavy load scenarios, if the task submitted by the user triggers the io switching coroutine, the coroutine where the idler is located cannot be scheduled in time. Therefore, use thread_yield to ensure the "relative" order of task execution.
=> use thread_yield instead of thread_yield_to in workerpool

common/alog.h, thread/test/test.cpp, thread/thread11.h
> invoke dtor for arguments passed to thread_create11() (#987) (#988)
Co-authored-by: Huiba Li <huiba.lhb@alibaba-inc.com>
=> [Pick][0.8 to 0.9] | invoke dtor for arguments passed to thread_create11() (#987) (#988) 

fs/test/test.cpp, thread/thread.cpp
> make thread_yield_to() less prone to starve threads (#982)
=> [Pick][0.7 to 0.8] | make thread_yield_to() less prone to starve threads (#982) 

thread/std-compat.h
> Fix photon_std::condition_variable not using custom clock for time_point (#1002)
=> [Pick][0.7 to 0.8] | Fix photon_std::condition_variable not using custom clock for time_point (#1002) 

thread/std-compat.h
> Fix photon_std::condition_variable not using custom clock for time_point (#1002) (#1004) (#1005)
Co-authored-by: NewbieOrange <NewbieOrange@users.noreply.github.com>
=> [Pick][0.9 to main] | Fix photon_std::condition_variable not using custom clock for time_point (#1002) (#1004) (#1005) 
